### ISSUE TITLE
RaftFleet.active_nodes() not updating

### ISSUE THREAD

**Issue by cs-victor-nascimento** [skirino/raft_fleet#2]
Hi again!

I'm trying to simulate nodes going up and down with `RaftFleet`. My setup is trying to put together `libcluster` and RaftFleet.

With `libcluster` I make the discovery of nodes automatically. Currently, when they start, they all activate on the same "zone1". After making a cluster of 4 nodes I get the following result from `RaftFleet.active_nodes()`:

```elixir
%{"zone1" => [:"node4@cs-victor-nascimento",
   :"node3@cs-victor-nascimento", :"node2@cs-victor-nascimento",
   :"node1@cs-victor-nascimento"]}
```

If I kill one node with C-c twice, this list does not get updated. Result:

```sh
iex(node1@cs-victor-nascimento)13> RaftFleet.active_nodes
%{"zone1" => [:"node4@cs-victor-nascimento", :"node3@cs-victor-nascimento",
   :"node2@cs-victor-nascimento", :"node1@cs-victor-nascimento"]}
iex(node1@cs-victor-nascimento)14> Node.list
[:"node2@cs-victor-nascimento", :"node4@cs-victor-nascimento"]
iex(node1@cs-victor-nascimento)15> 
```

Even after waiting a little while... Am I missing anything here?

Thanks once again for your work!

**Comment by skirino** [comment]
Hi,

As raft_fleet uses only ErlangVM-to-ErlangVM connections as source of information on running ErlangVMs (at least in its current version), even if you know that a node is dead (because you hit "C-c"), running nodes are not certain whether the node is "actually dead" or "still running on the other side of netsplit".
In the case of netsplit there are cases where simply discarding disconnected node(s) results in loss of committed writes.

Based on the above considerations, raft_fleet takes a fairly conservative approach regarding node cleanup, i.e., it does almost nothing.
Thus, in general, when a node has gone down you have to manually call e.g. `RaftFleet.remove_dead_pids_located_in_dead_node/1`.

Having said that, raft_fleet does one thing: it automatically purges "unhealthy" node.
Here "unhealthy" node means a node where many unresponsive member processes reside.
This feature is made to automatically recover from rather simple failure scenarios.

To see whether this is what you need, please try again with e.g. 10 consensus groups (assuming replication factor of 3, 30 processes in 4 nodes).
Once you kill a node, approximately 8 processes in that node will become unresponsive and the remaining 3 nodes start to consider that node as "unhealthy".
After ~10 minutes the node is removed from `RaftFleet.active_nodes/0`.
See also [`RaftFleet.Config`](https://hexdocs.pm/raft_fleet/RaftFleet.Config.html).

**Comment by skirino** [comment]
In 0.5.0 release I made an automatic cleanup mechanism to recover from permanent failures.
After killing a node in a cluster, after a configurable interval (by default 10 minutes), remaining nodes regard the killed node as "dead" and remove it from `RaftFleet.active_nodes/0`.
Closing this, hoping that helps you!
